#!/bin/sh
# dirname $0，取得当前执行的脚本文件的父目录，cd到父目录，即进入当前工作目录，pwd显示当前工作目录
cd $(dirname $0)
str=" abc, error ,aaa , bbbb"
arr=(${str//error/})
echo ${arr[@]}
for((i=0;i<=${#arr};i++))
do
    echo "$i"
    echo "${arr[i]}"
done
